services:
  postgres:
      image: postgres:17
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # healthcheck:
      #   test: ["CMD-SHELL", "pg_isready -U postgres"]
      #   interval: 10s
      #   timeout: 5s
      #   retries: 5
  
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    # healthcheck:
    #   test: ["CMD", "mosquitto_sub", "-h", "localhost", "-t", "health", "-C", "1"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

  publisher:
    build:
      context: .
      dockerfile: dockerfile.publisher
    depends_on:
      - mosquitto
      # mosquitto:
      #   condition: service_healthy
    environment:
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
      MQTT_KEEPALIVE: 60
      TOPIC: sensor/value
      INTERVAL: 5

  subscriber:
    build:
      context: .
      dockerfile: dockerfile.subscriber
    depends_on:
      - mosquitto
      - postgres
      # mosquitto:
      #   condition: service_healthy
      # postgres:
      #   condition: service_healthy
    environment:
      PG_HOST: postgres
      PG_DB: postgres
      PG_USER: postgres
      PG_PASSWORD: postgres
      TOPIC: sensor/value
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
      MQTT_KEEPALIVE: 60

volumes:
  pgdata:
